### ISSUE TITLE
Use Hugo Extended

### ISSUE THREAD

**Issue by onweru** [uracreative/briar-styleguide#1]
Seeing that we're using [sass](https://github.com/uracreative/briar-styleguide/tree/hugo/assets), we'll need to use Hugo extended. That's what I use by default 😊.

**Comment by elioqoshi** [comment]
That is Chinese to me unfortunately :p

@AnXh3L0 ?

**Comment by AnXh3L0** [comment]
Sounds good to me

**Comment by AnXh3L0** [comment]
We are now using Hugo Extended. Closing.
